# Generated by Django 3.2.10 on 2024-06-09 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='latin1_swedish_ci', max_length=20)),
                ('product_name', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=20, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bust', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=255, null=True)),
                ('habit', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=255, null=True)),
                ('value', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=255, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('valid', models.IntegerField(blank=True, null=True)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flower',
                'managed': True,
            },
        ),
    ]
